services:
  - type: web
    name: mangafox-api
    runtime: node
    buildCommand: npm install
    startCommand: node server/index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3002
      - key: API_BASE_URL
        value: https://mangadex-i6sv.onrender.com
